"""initial schema

Revision ID: 935a36617e5d
Revises:
Create Date: 2026-03-24 00:11:11.277112
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "935a36617e5d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ml_models",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("model_path", sa.String(length=1024), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ml_models_name"), "ml_models", ["name"], unique=True)
    op.create_table(
        "inference_endpoints",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("model_id", sa.Uuid(), nullable=False),
        sa.Column("runtime", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("kserve_name", sa.String(length=255), nullable=False),
        sa.Column("namespace", sa.String(length=255), nullable=False),
        sa.Column("instance_type", sa.String(length=50), nullable=False),
        sa.Column("replicas", sa.Integer(), nullable=False),
        sa.Column("gpu", sa.Boolean(), nullable=False),
        sa.Column("cpu", sa.String(length=20), nullable=False),
        sa.Column("memory", sa.String(length=20), nullable=False),
        sa.Column("logger_enabled", sa.Boolean(), nullable=False),
        sa.Column("logger_mode", sa.String(length=20), nullable=True),
        sa.Column("logger_destination", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["model_id"], ["ml_models.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inference_endpoints_name"),
        "inference_endpoints",
        ["name"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inference_endpoints_name"), table_name="inference_endpoints")
    op.drop_table("inference_endpoints")
    op.drop_index(op.f("ix_ml_models_name"), table_name="ml_models")
    op.drop_table("ml_models")
    # ### end Alembic commands ###
